### ISSUE TITLE
Can't send funds - "Send Funds" button is stuck

### ISSUE THREAD

**Issue by realrover** [OmniLayer/omniwallet#1258] opened 2016-03-06 04:13 UTC
Tried different browsers, but when I press "send funds" it shows "waiting" gif and nothing happens. Window remains open. Please help!

**Comment by federicoon** [comment] 2016-03-06 14:37
Same to me! This is a severe issue, please give us some feedback asap!

**Comment by cfp23** [comment] 2016-03-07 03:22
Ditto. I am having the same issues and have tried Chrome and Firefox. Have even tried varying amounts of tx fees.

**Comment by achamely** [comment] 2016-03-07 16:37
Hey Folks ( @realrover @federicoon @cfp23 ), 

Please close all your chrome browser's (even reboot if possible) and then open 1 fresh/clean new browser. (If this is not possible then please open a new chrome browser in incognito mode)

Before navigating to any page open the developer console and go to the '**console**' tab and make sure '**Preserve log**' option is checked. 
 (developer.chrome.com/devtools/docs/console#opening-the-console)

Proceed as normal to omniwallet, login , wait for the main page to load your balance information, then navigate to the send page and attempt your transaction again.

If the issue persists, please copy the entire output from the Developer Console and email us (https://www.omniwallet.org/about/contact) with the log info, the address you were sending from, address sending to, amount, coin type and approx time you attempted your send so we can check the logs and compare / track whats going on.

**Comment by federicoon** [comment] 2016-03-07 17:31
What about this:
`TypeError: parseScript is not a function
    at $scope.TxPromise.then.$modalScope.sendError (TransactionGenerationController.js:31)
    at wrappedCallback (angular.js:11659)
    at wrappedCallback (angular.js:11659)
    at angular.js:11745
    at Scope.$eval (angular.js:12788)
    at Scope.$digest (angular.js:12600)
    at Scope.$apply (angular.js:12892)
    at done (angular.js:8427)
    at completeRequest (angular.js:8641)
    at XMLHttpRequest.xhr.onreadystatechange (angular.js:8580)
`
I'm not a Javascript developer, but at TransactionGenerationController.js:31 I see a call to the function parseScript(script), which doesn't look to me within the scope of the caller block.
But I might be wrong, it's a too messy language to me...

**Comment by Verve435** [comment] 2016-03-07 17:37
Same issue. Just gets stuck when I click send. Tried firefox and chrome. Mailed you, hope this is fixed soon.

**Comment by achamely** [comment] 2016-03-07 20:14
Thanks guys, we are looking into it now. 
Can you do one more thing.
If possible, Can you let us know what version of chrome you are using and what os .

**Comment by Verve435** [comment] 2016-03-07 20:23
Chrome Version 49.0.2623.75 m

Win 7 64bit


Cheers

________________________________

**Comment by realrover** [comment] 2016-03-07 21:05
Version 49.0.2623.75 (64-bit)
Ubuntu 15.10

**Comment by achamely** [comment] 2016-03-07 21:44
And there it is, confirmed the issue was introduced with Chrome Version 49.0.2623.75 (64-bit)
Tests on Chrome Version 48.0.2564.116 m  do not exhibit the same issue. 

Working on tracking down what's changed and fix it.

**Comment by achamely** [comment] 2016-03-07 22:08
OK guys, i think i've got a patch in place now.  Looks like the new update to chrome changed the way it interprets some function declarations. I had to move some around to get it to recognize them.   Try and see if the issue is resolved now.

**Comment by realrover** [comment] 2016-03-07 22:15
OK, Chrome works now for me. But the same problem was with Firefox. I didn't check it now however.

**Comment by Verve435** [comment] 2016-03-07 22:15
Tried but still the same prob.

**Comment by achamely** [comment] 2016-03-07 22:17
Yes Firefox seems to have an issue where it can't interpret the signing library we use to finish the transaction.  
@realrover for now please use chrome. 
@Verve435   which browser did you use/try.  Chrome or firefox?

**Comment by Verve435** [comment] 2016-03-07 22:17
Works on chrome, thanks!
Still not working on firefox.

**Comment by achamely** [comment] 2016-03-07 22:20
Ok great.  We are working on the firefox related issue,  that will take some more time as it's related to an issue with the signing library.  For now i'm going to mark this bug resolved with #1259 and track firefox specific one separate.

**Closed by achamely** 2016-03-07 22:20 UTC
Labels: Bug
